"""empty message

Revision ID: 1a1cd0803982
Revises: cde90d12b095
Create Date: 2022-09-04 18:49:25.161647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1cd0803982'
down_revision = 'cde90d12b095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideal_chest_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideal_chest_name'))
    )
    op.create_table('ideal_chest_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideal_chest_type'))
    )
    op.drop_table('ideal_chest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideal_chest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('path', sa.VARCHAR(length=64), nullable=True),
    sa.Column('text', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_ideal_chest')
    )
    op.drop_table('ideal_chest_type')
    op.drop_table('ideal_chest_name')
    # ### end Alembic commands ###
