"""empty message

Revision ID: 28cdf72ae455
Revises: 2eb6f5c21c98
Create Date: 2022-09-07 19:11:52.977706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cdf72ae455'
down_revision = '2eb6f5c21c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_player', schema=None) as batch_op:
        batch_op.drop_column('league')

    # ### end Alembic commands ###
