"""empty message

Revision ID: 2a2fc0ae24bf
Revises: d92f169841c8
Create Date: 2022-03-20 21:32:20.175096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2fc0ae24bf'
down_revision = 'd92f169841c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chest', sa.Column('opened_in', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chest', 'opened_in')
    # ### end Alembic commands ###
