"""empty message

Revision ID: 2eb6f5c21c98
Revises: d704f1b2dff2
Create Date: 2022-09-04 23:10:57.993299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb6f5c21c98'
down_revision = 'd704f1b2dff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chest', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
