"""empty message

Revision ID: 3a17b06fc88d
Revises: 908e20491918
Create Date: 2023-01-03 13:48:18.074607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a17b06fc88d'
down_revision = '908e20491918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('log_cookie')
        batch_op.drop_column('cookieyesID')
        batch_op.drop_column('PTBHSSID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PTBHSSID', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('cookieyesID', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('log_cookie', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
