"""empty message

Revision ID: a31b32dd21b0
Revises: f5ebf59430aa
Create Date: 2022-04-27 15:37:24.357757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31b32dd21b0'
down_revision = 'f5ebf59430aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
