"""queue upgrade

Revision ID: ad70f8ab04e2
Revises: a282763d9910
Create Date: 2023-06-06 14:20:59.962613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad70f8ab04e2'
down_revision = 'a282763d9910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('url', sa.String(length=128), nullable=True))
    op.add_column('queue', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('queue', sa.Column('cookies', sa.String(length=256), nullable=True))
    op.add_column('queue', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('queue', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('queue', sa.Column('done', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'queue', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queue', type_='foreignkey')
    op.drop_column('queue', 'done')
    op.drop_column('queue', 'timestamp')
    op.drop_column('queue', 'active')
    op.drop_column('queue', 'cookies')
    op.drop_column('queue', 'account_id')
    op.drop_column('queue', 'url')
    # ### end Alembic commands ###
