"""empty message

Revision ID: e0b0edcd593b
Revises: 34a54a957b07
Create Date: 2022-08-31 19:52:58.415966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b0edcd593b'
down_revision = '34a54a957b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_player', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
