"""empty message

Revision ID: f5ebf59430aa
Revises: 2a2fc0ae24bf
Create Date: 2022-03-29 10:37:35.236287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ebf59430aa'
down_revision = '2a2fc0ae24bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_locked')
    # ### end Alembic commands ###
