"""empty message

Revision ID: 2005593eaf51
Revises: 3a17b06fc88d
Create Date: 2023-01-03 14:04:43.741008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2005593eaf51'
down_revision = '3a17b06fc88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selenium_url', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('selenium_session_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('selenium_session_id')
        batch_op.drop_column('selenium_url')

    # ### end Alembic commands ###
