"""empty message

Revision ID: 3b10c9efc8b8
Revises: 77a6b2aa0d1a
Create Date: 2022-04-27 15:49:49.963186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b10c9efc8b8'
down_revision = '77a6b2aa0d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('query', sa.VARCHAR(length=64), nullable=True),
    sa.Column('hash', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
