"""empty message

Revision ID: 4958951f266b
Revises: 5e78b00ea0e5
Create Date: 2022-08-26 14:18:35.680246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4958951f266b'
down_revision = '5e78b00ea0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('report_query', sa.String(length=64), nullable=True))
        # batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('query', sa.VARCHAR(length=64), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_column('report_query')

    # ### end Alembic commands ###
