"""empty message

Revision ID: 5055e0faaf9a
Revises: 761d10e8252d
Create Date: 2022-09-10 14:30:49.449634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5055e0faaf9a'
down_revision = '761d10e8252d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chest', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chest_player_id_clan_player', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_chest_player_id_clan_player'), 'clan_player', ['player_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chest', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chest_player_id_clan_player'), type_='foreignkey')
        batch_op.create_foreign_key('fk_chest_player_id_clan_player', 'clan_player', ['player_id'], ['id'])

    # ### end Alembic commands ###
