"""empty message

Revision ID: 50ba70c9dd1e
Revises: c337f3c137b9
Create Date: 2022-12-15 01:40:04.171394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ba70c9dd1e'
down_revision = 'c337f3c137b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chest_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ideal_chest_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('ideal_chest_type', sa.String(length=64), nullable=True))
        batch_op.drop_column('ideal_chest_naming')
        batch_op.drop_column('type_of_selection')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chest_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_selection', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('ideal_chest_naming', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('ideal_chest_type')
        batch_op.drop_column('ideal_chest_name')

    # ### end Alembic commands ###
