"""empty message

Revision ID: 7af5debd5125
Revises: 2005593eaf51
Create Date: 2023-01-10 12:43:07.782389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af5debd5125'
down_revision = '2005593eaf51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_query', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_report_account_id_account'), 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_report_account_id_account'), type_='foreignkey')
        batch_op.drop_column('account_id')
        batch_op.drop_column('report_query')

    # ### end Alembic commands ###
