"""empty message

Revision ID: 95a507be7f43
Revises: 7af5debd5125
Create Date: 2023-01-10 13:53:29.156820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a507be7f43'
down_revision = '7af5debd5125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_needed', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chest', schema=None) as batch_op:
        batch_op.drop_column('check_needed')

    # ### end Alembic commands ###
