"""empty message

Revision ID: c337f3c137b9
Revises: eb39742e995c
Create Date: 2022-12-07 00:52:34.427496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c337f3c137b9'
down_revision = 'eb39742e995c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chest_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('type_of_selection', sa.String(length=64), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('scores', sa.Integer(), nullable=True),
    sa.Column('ideal_chest_naming', sa.String(length=64), nullable=True),
    sa.Column('ideal_chest_name_id', sa.Integer(), nullable=True),
    sa.Column('ideal_chest_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_chest_rule_account_id_account')),
    sa.ForeignKeyConstraint(['ideal_chest_name_id'], ['ideal_chest_name.id'], name=op.f('fk_chest_rule_ideal_chest_name_id_ideal_chest_name')),
    sa.ForeignKeyConstraint(['ideal_chest_type_id'], ['ideal_chest_type.id'], name=op.f('fk_chest_rule_ideal_chest_type_id_ideal_chest_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chest_rule'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chest_rule')
    # ### end Alembic commands ###
