"""empty message

Revision ID: d704f1b2dff2
Revises: 1a1cd0803982
Create Date: 2022-09-04 19:00:18.610691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd704f1b2dff2'
down_revision = '1a1cd0803982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chest_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('got_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chest_chest_name'), ['chest_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chest_chest_name'))
        batch_op.drop_column('got_at')
        batch_op.drop_column('chest_name')

    # ### end Alembic commands ###
