"""empty message

Revision ID: d92f169841c8
Revises: d9b7e2d3a885
Create Date: 2022-03-17 21:47:42.237545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92f169841c8'
down_revision = 'd9b7e2d3a885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('chest_type', sa.String(length=64), nullable=True),
    sa.Column('player', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chest_chest_type'), 'chest', ['chest_type'], unique=False)
    op.create_index(op.f('ix_chest_player'), 'chest', ['player'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chest_player'), table_name='chest')
    op.drop_index(op.f('ix_chest_chest_type'), table_name='chest')
    op.drop_table('chest')
    # ### end Alembic commands ###
